import { type Theme, webLightTheme } from "@fluentui/react-components";

export const strattonTheme: Theme = {
  ...webLightTheme,
  colorBrandBackground: "#0b223b",
  colorBrandBackground2: "#e8edf2",
  colorBrandBackgroundHover: "#123452",
  colorBrandBackgroundPressed: "#07182a",
  colorBrandForeground1: "#0b223b",
  colorBrandForeground2: "#8c6d2d",
  colorBrandForegroundLink: "#0b4f82",
  colorBrandForegroundLinkHover: "#07395e",
  colorBrandStroke1: "#9a7932",
  colorBrandStroke2: "#c7b27d",
  colorNeutralBackground1: "#ffffff",
  colorNeutralBackground2: "#f7f6f2",
  colorNeutralBackground3: "#efeee9",
  colorNeutralBackground4: "#e6e5df",
  colorNeutralBackground5: "#dad9d2",
  colorNeutralBackground6: "#cccbc3",
  colorNeutralForeground1: "#17202b",
  colorNeutralForeground2: "#495463",
  colorNeutralForeground3: "#66717e",
  colorNeutralForeground4: "#7c8793",
  colorNeutralForegroundOnBrand: "#ffffff",
  colorNeutralStroke1: "#d3d0c7",
  colorNeutralStroke2: "#e4e1d9",
  colorNeutralStroke3: "#efede7",
  colorNeutralStrokeOnBrand: "#ffffff",
  colorPaletteGreenForeground1: "#17633a",
  colorPaletteGreenBackground1: "#e8f3ec",
  colorPaletteRedForeground1: "#a12b2b",
  colorPaletteRedBackground1: "#f8e9e8",
  colorPaletteYellowForeground1: "#725610",
  colorPaletteYellowBackground1: "#f6f0dd",
  colorPaletteDarkOrangeForeground1: "#8c4c18",
  colorPaletteDarkOrangeBackground1: "#f6eadf",
  fontFamilyBase: '"Aptos", "Segoe UI", Calibri, Arial, sans-serif',
  fontFamilyMonospace: 'Consolas, "Courier New", monospace',
  borderRadiusSmall: "2px",
  borderRadiusMedium: "4px",
  borderRadiusLarge: "8px",
  borderRadiusXLarge: "10px",
  shadow2: "0 1px 2px rgba(13, 31, 49, 0.08)",
  shadow4: "0 2px 8px rgba(13, 31, 49, 0.08)",
  shadow8: "0 8px 24px rgba(13, 31, 49, 0.10)"
};
